all:
	nvcc src.cu -o exe

send:
	@echo password: nqxvWE
	scp -r -P 2210 ../At.07-4 ssc903-ta-g01@andromeda.lasdpc.icmc.usp.br:/home/ssc903-ta-g01

connect:
	@echo password: nqxvWE
	ssh ssc903-ta-g01@andromeda.lasdpc.icmc.usp.br -p 2210